### ISSUE TITLE
Is is ok to submit models with additional dependency?

### ISSUE THREAD

**Issue by lime-j** [amumu1843/Robust_Raw_Object_Detection#2]
Dear authors,

The testing phase is approaching, and I wonder if it is okay to utilize additional Python packages, say, numpy, opencv-python, etc. If it is okay, how can we define the requirements? Besides, can we use hand-written CUDA operators (which requires an additional compilation procedure defined in setup.py of a Python package) to make the best use of the testing device?

**Comment by amumu1843** [comment]
@lime-j Thanks for your reminding. I have just changed the starting command from `python main.py` to `bash start.sh`. Please install all dependencies (including python packages and self-written libraries) at the bash script. We also provide an example [here](https://github.com/amumu1843/Robust_Raw_Object_Detection/blob/main/codes/example_start_eval.sh).

**Comment by lime-j** [comment]
Thank you for your reply!
